### ISSUE TITLE
Move docker host to lxc

### ISSUE THREAD

**Issue by crankiz** [crankiz/homelab#8]

**Comment by crankiz** [comment]
## Investigate
- [ ] Pros/Cons
- [ ] Time estimation
- [ ] Risk analysis

**Comment by crankiz** [comment]
## Subtasks
- [ ] Create lxc with with terraform.
- [ ] Mount volume with all docker volumes so data will be presistent between deploys.
- [ ] Setup proxmox and nginx proxy manager/treafik
